from pathlib import Path

DIR_WITH_TEST_FILES = Path(__file__).parent / "test_data"

DIR_WITH_PREPARERS_TEST_FILES = DIR_WITH_TEST_FILES / "preparers"

DIR_WITH_DIRECTORY_GENERATOR_TEST_FILES = DIR_WITH_PREPARERS_TEST_FILES / "dir_preparer"
DIR_WITH_INPUT_FILES_FOR_TESTING_DIRECTORY_GENERATOR = DIR_WITH_DIRECTORY_GENERATOR_TEST_FILES / "input_files"
DIR_WITH_GOLD_STANDARD_DIRS_FOR_TESTING_DIRECTORY_GENERATOR = DIR_WITH_INPUT_FILES_FOR_TESTING_DIRECTORY_GENERATOR / "gold_standard"
